### PR TITLE
perf: add "sideEffects" flag to package.json

### PR DESCRIPTION
**Pull request by FezVrasta**
Adds the "sideEffects" flag to `package.json`.

I tested this on my local create-react-app project and it works correctly.

Before:
image

After:
image

Closes issue: #114

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Code is reviewed for security

### CODE REVIEW

**Comment by stephenmathieson** [comment]
I don't think this is necessary, since react-axe shouldn't be included in production bundles. It's development-only software.

**Comment by FezVrasta** [comment]
@stephenmathieson please read the related issue, I explained the reasoning behind

**Comment by stephenmathieson** [comment]
Right, I saw the issue, but you shouldn't be including react-axe in your production bundle to begin with. Instead, use the strategy described in the README:

```js
import React from 'react'
import ReactDOM from 'react-dom'

if (process.env.NODE_ENV !== 'production') {
  const axe = require('react-axe');
  axe(React, ReactDOM, 1000);
}
```

We do not support using react-axe in production bundles, because it is a development-only tool.

**Comment by FezVrasta** [comment]
My project doesn't use RequireJS, just ES Modules.

We don't include the package in the production bundle, given my PR gets merged.

**Comment by FezVrasta** [comment]
The purpose of sideEffects is to let webpack strip out dependencies if they are not used for whatever reason.

This use case perfectly fits.

This is course is valid only if this package is really side effects free, which from what I see, it is.

Honestly I don't understand why your are so reluctant to add this flag. It's never going to cause any harm but it will help people that use bundlers without requirejs

About that, `require` **is** Requirejs, webpack simply supports it.

But if I used Rollup, without the commonjs plugin, the `require` call wouldn't work.

So I don't understand why you want to force your users to adopt either requirejs or commonjs when with just a flag you can support native ES modules?

**Comment by WilcoFiers** [comment]
@FezVrasta The only way that the `sideEffects` flag can work is through Webpack. And since Webpack supports CommonJS module loading by default, using `require` will work as a solution in any environment where you are using Webpack. If you want to use strictly valid ES modules, we recommend using `import()`, which is also [available in Webpack](https://webpack.js.org/api/module-methods/#import-1).

There are a few reasons we are hesitant to add this feature.

1. Using `require` inside an `process.env.NODE_ENV !== 'production'` is the most widely support way of using react-axe, unlike relying on tree shaking through `sideEffects` which only works in Webpack.

2. We do not feel that supporting multiple ways of solving the same problem is an improvement to software. It increases the cognitive load on developers, and it increases the overhead of maintenance.

Adding this would mean we'd either have to document that there are now two recommended ways of using react-axe, or we'd have an undocumented feature. This does not seem like the right solution for react-axe to us. I do very much appreciate the pull request. But at the moment this is not a change we think is right for react-axe.

**Comment by FezVrasta** [comment]
Even Rollup supports this flag. And it doesn't support commonjs out of the box.

Dynamic imports are not a solution. They are not the equivalent of `require`. They are completely asynchronous.

**Pull request closed without merging**
