### PR TITLE
fix: Fire debounced checkNode on leading edge

### PR DESCRIPTION
**Pull request by JiaboHou**
Taken from @dambusm's [fork](https://github.com/dambusm/react-axe/commit/63cbf0fa1dda51250c5925143fef64ca252ddb7e)

This PR fixes issues with checking unmounted nodes and the resulting console errors.

Example console error:
image

Closes issue: #144 

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [ ] Follows the commit message policy, appropriate for next version
- [ ] Code is reviewed for security

### CODE REVIEW

**Comment by straker** [comment]
Thanks for the pr. @dambusm have you noticed any issues with firing on the leading edge? Does getting the results first, but not again until the end of the debounce timer cause any confusion?

**Comment by dambusm** [comment]
> Thanks for the pr. @dambusm have you noticed any issues with firing on the leading edge? Does getting the results first, but not again until the end of the debounce timer cause any confusion?

I'm afraid I haven't had time to test it properly so far, hence not submitting it as a PR myself. I am going to try and grab some time today to play around with it some more and write up some tests.

**Comment by straker** [comment]
@dambusm any update? If not I think I'm going to merge the pr by end of day.

**Comment by dambusm** [comment]
I wasn't able to write any tests unfortunately, but I've been using a build with this change on my production project and haven't noticed any ill effects, and the console errors are definitely gone.

**Pull request merged**
