### PR TITLE
fix: use a semaphore to avoid running axe concurrently

### LINKED ISSUE #32: Expect axe._selectorData to be set up
Don't know if this is because of axe-core or react-axe

screen shot 2018-04-04 at 12 51 33

### PR DESCRIPTION
**Pull request by stephenmathieson**
A previous commit (1d4bd8db521d38f4fba831e3066339dc21d31325) removed our pseudo-semaphore which prevented us from running aXe concurrently. This patch adds back our "timer" semaphore and ensures we do not can `axe.run()` more than once on the same tick.

Closes #32.

### CODE REVIEW

**Comment by dylanb** [comment]
I would love to see tests for this too...but given we don't have any yet, am willing to defer that to fix this critical issue

**Comment by stephenmathieson** [comment]
I agree that tests would be great. I'm happy to work on creating a test suite for this package, but I'm with Dylan here and think we ought to get this fixed for our customers first.

**Comment by badtant** [comment]
don't forget to put the timeout back in the readme

**Comment by stephenmathieson** [comment]
Whoops, good catch @badtant!

**Pull request merged**
